name: Build and Push Docker Image to GitHub Packages

on:
  push:
    branches:
      - main # 触发构建的分支，这里设置为主分支
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Login to GitHub Package Registry
      run: echo "${{ secrets.GHCR_PASSWORD }}" | docker login docker.pkg.github.com -u ${{ secrets.GHCR_USERNAME }} --password-stdin

    - name: Build the Docker image
      run: docker build -f Docker/Dockerfile -t docker.pkg.github.com/magisk317/XYBot/XYBot:latest .

    - name: Tag the Docker image
      run: |
        IMAGE_NAME=docker.pkg.github.com/magisk317/XYBot/XYBot
        IMAGE_TAG=$(date +%s)
        echo "Tagging $IMAGE_NAME:$IMAGE_TAG"
        docker tag docker.pkg.github.com/magisk317/XYBot/XYBot:latest $IMAGE_NAME:$IMAGE_TAG

    - name: Push the Docker image
      run: |
        IMAGE_NAME=docker.pkg.github.com/magisk317/XYBot/XYBot
        IMAGE_TAG=$(date +%s)
        docker push $IMAGE_NAME:$IMAGE_TAG
